spring:
    datasource:
        password:
        url:
        username:
    mail:
        host:
        port:
        username:
        password:
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: create-drop
        database: mysql
    quartz:
        job-store-type: jdbc
        jdbc:
            initialize-schema: always
        jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driveDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            dataSource: myDS
            tablePrefix: QRTZ_
        threadPool:
            threadCount: 5

application:
    security:
        jwt:
            secret-key:
            expiration: 86400000 # 1 day in milliseconds
            refresh-token:
                expiration: 604800000 # 1 week in milliseconds

firebase:
    enabled: true

logging:
    level:
        org:
            springframework:
                jdbc: DEBUG